debug: true

logging:
  level:
    com:
      netflix: DEBUG

spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      :percentage: 1.0
    :web:
      :skipPattern: (^cleanup.*|.+favicon.*)


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true


server:
  port: 2020

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000
  eureka:
    enabled: true   #important

zuul:
  routes:

    transactions-query:
      path: /api/transactions/full/**
      serviceId: TRANSACTION-AGGREGATION-SERVICE
      strip-prefix: false


    transactions-command:
      ignoredPatterns: /api/transactions/full/**
      path: /api/transactions/**
      serviceId: TRANSACTION-SERVICE
      strip-prefix: false



